import { readFileSync } from "node:fs";

import eleventyNavigationPlugin from "@11ty/eleventy-navigation";
import rss from "@11ty/eleventy-plugin-rss";
import syntaxHighlight from "@11ty/eleventy-plugin-syntaxhighlight";
import { minify as htmlMinify } from "html-minifier-terser";
import { load as yamlLoad } from "js-yaml";
import markdownIt from "markdown-it";
import removeMarkdown from "remove-markdown";

const globalData = yamlLoad(readFileSync("src/data/global.yml", "utf8"));

const markdown = markdownIt({
  html: true,
});

const paths = {
  posts: "src/posts/*/index.md",
  blog: "src/blog/*/index.md",
  pages: "src/pages/!(404)/**/index.njk",
};

const sectionNames = ["work", "javascript", "algorithms"];

const sortByDateDescending = (items = []) => {
  return [...items].sort((a, b) => b.date - a.date);
};

const getSectionItems = (collectionApi, section) => {
  return sortByDateDescending(
    collectionApi
      .getFilteredByGlob(paths.posts)
      .filter((item) => item.data.section === section),
  );
};

const getSectionTags = (collectionApi, section) => {
  const tags = new Set();

  getSectionItems(collectionApi, section).forEach((item) => {
    const itemTags = Array.isArray(item.data.tags) ? item.data.tags : [];

    itemTags.forEach((tag) => {
      if (!["all", "posts", section].includes(tag)) {
        tags.add(tag);
      }
    });
  });

  return [...tags].sort((a, b) => a.localeCompare(b));
};

export default function (eleventyConfig) {
  // Collections

  eleventyConfig.addCollection("posts", (collectionApi) => {
    return sortByDateDescending(collectionApi.getFilteredByGlob(paths.posts));
  });

  eleventyConfig.addCollection("blog", (collectionApi) => {
    return sortByDateDescending(collectionApi.getFilteredByGlob(paths.blog));
  });

  sectionNames.forEach((section) => {
    eleventyConfig.addCollection(section, (collectionApi) => {
      return getSectionItems(collectionApi, section);
    });

    eleventyConfig.addCollection(`${section}Tags`, (collectionApi) => {
      return getSectionTags(collectionApi, section);
    });
  });

  eleventyConfig.addCollection("sectionTags", (collectionApi) => {
    return sectionNames.flatMap((section) =>
      getSectionTags(collectionApi, section).map((tag) => ({
        section,
        tag,
      })),
    );
  });

  eleventyConfig.addCollection("sitemap", (collectionApi) => {
    return collectionApi.getFilteredByGlob([
      paths.posts,
      paths.blog,
      paths.pages,
    ]);
  });

  // YAML

  eleventyConfig.addDataExtension("yml", (contents) => {
    return yamlLoad(contents);
  });

  // Plugins

  eleventyConfig.addPlugin(rss);

  eleventyConfig.addPlugin(syntaxHighlight, {
    alwaysWrapLineHighlights: true,
  });

  eleventyConfig.addPlugin(eleventyNavigationPlugin);

  // HTML

  eleventyConfig.addTransform("html-minify", async (content, outputPath) => {
    if (!outputPath?.endsWith(".html")) {
      return content;
    }

    return htmlMinify(content, {
      collapseBooleanAttributes: true,
      collapseWhitespace: true,
      decodeEntities: true,
      includeAutoGeneratedTags: false,
      removeComments: true,
    });
  });

  // Data cascade

  eleventyConfig.setDataDeepMerge(true);

  // Static files

  [
    "src/assets",
    "src/images",
    "src/posts/**/images",
    "src/posts/**/assets",
    "src/blog/**/images",
    "src/blog/**/assets",
    "src/manifest.json",
    "src/blog/**/i",
    "CNAME",
    "robots.txt",
  ].forEach((path) => {
    eleventyConfig.addPassthroughCopy(path);
  });

  // Content filters

  eleventyConfig.addFilter("readTime", (value = "") => {
    const textOnly = String(value)
      .replace(/<[^>]*>/g, " ")
      .trim();

    const words = textOnly.split(/\s+/).filter(Boolean).length;

    const wordsPerMinute = 200;

    return Math.max(1, Math.ceil(words / wordsPerMinute));
  });

  eleventyConfig.addFilter("sortByDateDesc", sortByDateDescending);

  eleventyConfig.addFilter("bySection", (items = [], section) => {
    return sortByDateDescending(
      items.filter((item) => item.data.section === section),
    );
  });

  eleventyConfig.addFilter("bySectionAndTag", (items = [], section, tag) => {
    return sortByDateDescending(
      items.filter((item) => {
        const tags = Array.isArray(item.data.tags) ? item.data.tags : [];

        return item.data.section === section && tags.includes(tag);
      }),
    );
  });

  // Dates

  eleventyConfig.addFilter("dateLong", (value) => {
    if (!value) {
      return "";
    }

    return new Date(value).toLocaleDateString("en", {
      dateStyle: "long",
    });
  });

  eleventyConfig.addFilter("dateShort", (value) => {
    if (!value) {
      return "";
    }

    const date = new Date(value);

    if (Number.isNaN(date.getTime())) {
      return "";
    }

    const articleYear = date.getFullYear();
    const currentYear = new Date().getFullYear();

    const dateFormat =
      articleYear < currentYear
        ? {
            month: "long",
            day: "numeric",
            year: "numeric",
          }
        : {
            month: "long",
            day: "numeric",
          };

    return date.toLocaleDateString("en", dateFormat);
  });

  eleventyConfig.addFilter("dateISO", (value) => {
    if (!value) {
      return "";
    }

    const date = new Date(value);

    if (Number.isNaN(date.getTime())) {
      return "";
    }

    return date.toISOString().slice(0, 10);
  });

  // Temp

  eleventyConfig.addFilter("htmlDateString", (value) => {
    if (!value) {
      return "";
    }

    const date = new Date(value);

    if (Number.isNaN(date.getTime())) {
      return "";
    }

    return date.toISOString().slice(0, 10);
  });

  // Absolute links

  eleventyConfig.addFilter("absolute", (content = "", post = {}) => {
    if (!globalData.domain || !post.url) {
      return content;
    }

    const baseUrl = new URL(post.url, globalData.domain);

    return String(content).replace(
      /(src|href)="(?!https?:\/\/|\/\/|#|mailto:|tel:)([^"]+)"/g,
      (match, attribute, url) => {
        const absoluteUrl = new URL(url, baseUrl);

        return `${attribute}="${absoluteUrl.href}"`;
      },
    );
  });

  // Markdown

  eleventyConfig.addFilter("markdownIt", (value = "") => {
    return markdown.render(String(value));
  });

  eleventyConfig.addFilter("markdownRemove", (value = "") => {
    return removeMarkdown(String(value));
  });

  eleventyConfig.setLibrary("md", markdown);

  return {
    dir: {
      input: "src",
      output: "dist",
      includes: "includes",
      layouts: "layouts",
      data: "data",
    },
    dataTemplateEngine: "njk",
    markdownTemplateEngine: "njk",
    htmlTemplateEngine: "njk",
    templateFormats: ["md", "njk"],
  };
}
